### ISSUE TITLE
GetAccounts: error unmarshalling json response body: parsing time

### ISSUE THREAD

**Issue by Bo0mer** [codatio/client-sdk-go#55]
Hi! I'm trying to use the SDK. When trying to get the list of Accounts for a particular company I get the following error:

```
error unmarshalling json response body: parsing time "2023-03-07T07:01:34" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"
```

It seems that the SDK does not like the response which is getting from the API.

Also, the docs says that I need to provide the API KEY in the `AuthHeader.APIKey` field. However, when providing the API key there it doesn't work. I was able to work around this by providing an `Basic <basic auth>` value.  

Following is the program I'm running:

```go
package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"net/http"

	codatio "github.com/codatio/client-sdk-go/accounting"
	"github.com/codatio/client-sdk-go/accounting/pkg/models/operations"
	"github.com/codatio/client-sdk-go/accounting/pkg/models/shared"
)

func main() {
	client := codatio.New(
		codatio.WithSecurity(
			shared.Security{
				AuthHeader: shared.SchemeAuthHeader{
					APIKey: "Basic <...omitted...>",
				},
			},
		))

	ctx := context.Background()

	listResp, err := client.Accounts.GetAccounts(ctx, operations.GetAccountsRequest{
		PathParams: operations.GetAccountsPathParams{
			CompanyID: "<...redacted...>,
		},
		QueryParams: operations.GetAccountsQueryParams{
			Page: 1,
		},
	})
	if err != nil {
		log.Fatalf("error listing accounts: %v", err)
	}

	if listResp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(listResp.RawResponse.Body)
		log.Fatalf("unexpected response code %d with body: %s", listResp.StatusCode, body)
	}

	fmt.Println(listResp.StatusCode)

	for _, r := range listResp.Links.Results {
		fmt.Println(r)
	}
}
```

`go.mod` file:

```
module codat-example

go 1.20

require github.com/codatio/client-sdk-go/accounting v0.4.3

require (
	github.com/cenkalti/backoff/v4 v4.2.0 // indirect
	github.com/codatio/client-sdk-go v0.0.0-20230308231546-197ad6b881e6 // indirect
)

```

Best,
Ivan

**Comment by dcoplowe** [comment]
Hi Ivan,

We will be releasing an update for this on Monday. I just wanted to add that this is currently an alpha release so please expect some changes to the library going forward. We're aiming to release a beta version sometime in April.

If you have any feedback on this library please let us know and we can look at incorporating them into the beta version.

Many thanks,

David

**Comment by Bo0mer** [comment]
This one has been fixed, Thanks.
